<?
$PERM["last-razd"]["2"]="D";
$PERM["last-razd"]["3"]="D";
$PERM["last-razd"]["4"]="D";
$PERM["last-razd"]["5"]="D";
$PERM["last-razd"]["*"]="D";
$PERM["last-el"]["2"]="D";
$PERM["last-el"]["3"]="D";
$PERM["last-el"]["4"]="D";
$PERM["last-el"]["5"]="D";
$PERM["last-el"]["*"]="D";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>